### ISSUE TITLE
13.04.01 - 13.04.03 Are sub questions now

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/DatabaseCatalogue#12]
<img width="858" alt="image" src="https://user-images.githubusercontent.com/7252105/56821561-f47bc280-684e-11e9-8962-ba6e28b01939.png">

The ls one missed the field. Not sure where the Clear Selection button is for.

**Comment by alina-trifan** [comment]
Not sure I understood. 13.04.01 - 13.04.03 should be questions and not sub-questions? The Clear Section is related to the comment field attached to 13.04.03 - will change it to textfield

**Comment by PRijnbeek** [comment]
They are now under 13.04 but should be 13.05, 13.06, 13.07 etc.

**Comment by PRijnbeek** [comment]
same for 13.07.01

**Comment by PRijnbeek** [comment]
same for 2.19.01.

**Comment by alina-trifan** [comment]
Done
