### ISSUE TITLE
14.11 Change text

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/DatabaseCatalogue#14]
Describe if additional information can be obtained from the patients (for example information about air pollution). We may also remove some of these questions (to be discussed)

**Comment by alina-trifan** [comment]
I changed the text. Will keep the issue open as a reminder for the discussion on whether we keep the questions or not.

**Comment by alina-trifan** [comment]
Will close the issue as I don't think the discussion will be continued here.
