### ISSUE TITLE
Unable to create New Entry

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/DatabaseCatalogue#17]
It was saving but at the end the Entry I made was not visible and all data was lost. I may not have the right permissions (but did see the New Entry button)

**Comment by PRijnbeek** [comment]
Apparently, it did save it and is available in the pull down (Is only shown when I open the Demo Workshop database by the way):

<img width="858" alt="image" src="https://user-images.githubusercontent.com/7252105/56822523-9b615e00-6851-11e9-9c12-5a6600d6e91f.png">

but when I look at ALL i do not see it:

<img width="858" alt="image" src="https://user-images.githubusercontent.com/7252105/56822622-eaa78e80-6851-11e9-9231-40ddcc4bc3e8.png">

Note I did two attempts but cannot access one of them. 

I then saw I still need to make it public by opening it again and see this:

<img width="858" alt="image" src="https://user-images.githubusercontent.com/7252105/56822784-699cc700-6852-11e9-9597-74100825e6c5.png">

After this I did see it, but  do not see all the sections?

**Comment by alina-trifan** [comment]
Done
