### ISSUE TITLE
Switch on the other Tabs

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/DatabaseCatalogue#18]
Can you switch on the other Tabs like publications etc so we can see the options that are there.

**Comment by alina-trifan** [comment]
Not sure I understand this. You mean the database plugins? Like Literature, Achilles, Jerboa, etc. in the EMIF Catalogue?

**Comment by PRijnbeek** [comment]
We call it the Database Catalogue from now on :), but yes indeed. Some will be empty though not sure how it will look like. On the one I created I see a document tab not sure why that is there and not in the one you created.

**Comment by alina-trifan** [comment]
Database Catalogue, right :) I switched on some of them. Seems like we have a bug in loading the Jerboa plugin in this installation, but I added the Achilles one. I suspect we only show the Documents tab if it is populated, but that is not in sync with the rest of the plugins so will look into it as a bug.

**Comment by PRijnbeek** [comment]
I see the Discussion one that works, the other two are greyed out. Did we not also have a Literature Tab?

**Comment by alina-trifan** [comment]
You should be seeing the other ones now. I made your user "Community Manager" - in EMIF only this user role would have access to those plugins (maybe that does not make sense in this context). I added the Literature plugin as well. This plugin gets populated with Publications added in the database, which are then annotated for biomedical terms based on a service developed within our group (you can have a look at the DEMO database in the DEMO community of the EMIF Catalogue). I can try to add a Publication section in the fingerprint template just for demonstration purposes.

**Comment by PRijnbeek** [comment]
Yes is a great feature indeed please add the publication section. We need to think about how to really use these annotations, but let's see later
