### ISSUE TITLE
Filling the questionnaire using API Calls

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/DatabaseCatalogue#24]
Can you explain to me how I can use the API to fill in a value, e.g. the number of active patients. We can then try to build an R package that runs against the CDM and then pushes the results to the catalogue.

**Comment by jloliveira** [comment]
Hi Peter,
you may access this information in the "API Information" option of the left panel and then "API Doc" button. However, please note that this interface only allows to add key-value pairs to extend the database metadata, not to fill in the fingerprint. The added info is used in searching operations and is shown in the "extra information" tab, when active. 
An API to update the fingerprint directly is something that we have in our ToDo list.
