### ISSUE TITLE
Rendering Visualisations

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/DatabaseCatalogue#28]
@jloliveira or @alina-trifan can you explain how the tab with Achilles results you created in EMIF works. I suppose this is driven from the JSON files and you have incorporated the Achilles Web code in some way? 

I know OHDSI is working on a visualizations package that will be used in all tools (not sure AchillesWeb is using it at the moment).

https://github.com/OHDSI/Visualizations

If that is the case it might be an option to use the Achilles Tab approach you already have to visualize the graphs we like to see as dashboard for the data sources?

Another option is the Jeboa tab approach where you rendered based on uploading a result file. This is nice since the data source can control the updates (we in case we select Achilles Tab approach we need that there as well)

Can you explain a bit how this currently works?

Thanks

**Comment by alina-trifan** [comment]
Hi Peter,

The Achilles plugin in the EMIF Catalogue is based on the Achilles Web, to which some of our former colleagues collaborated in the past. Achilles Web is displayed in an iframe inside the Catalogue. 

For the Jerboa graphs, we used chart.js. 

We will definitely check the Visualizations package but by the look of the AchillesWeb repo, there haven't been any recent updates.

**Comment by PRijnbeek** [comment]
Ok does this mean you have one Achilles Web service running on the server that hosts multiple folders (one for each database) which you then show driven by the database that is selected?

**Comment by PRijnbeek** [comment]
I think Achilles Web is not actively developed anymore by OHDSI so we may need to revisit this. To be discussed what the best options are.
