### ISSUE TITLE
2.0.6 The labels are containing {..}

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/DatabaseCatalogue#3]
<img width="790" alt="image" src="https://user-images.githubusercontent.com/7252105/56820146-6c47ee00-684b-11e9-8c29-89e716a5c248.png">

It also looks like the other is there twice (with and with free field)

**Comment by PRijnbeek** [comment]
pubic -> public

**Comment by PRijnbeek** [comment]
should not be checkbox but multiple..

**Comment by alina-trifan** [comment]
I had corrected all these glitches in the template and then I uploaded a previous version, without the corrections :( Will correct them in time for the workshop.

**Comment by PRijnbeek** [comment]
Great should be easy fixes.

**Comment by alina-trifan** [comment]
This one is done
