### ISSUE TITLE
Issues when creating/saving new entry

### ISSUE THREAD

**Issue by MaximMoinat** [EHDEN/DatabaseCatalogue#32]
Expected:
Upon creating a new entry, I can fill out all the forms in the fingerprint.

Observed:
The first page can be filled in, but when going to the next page, the system 
On first click it gives the message 'Saved with success'.
On second click of 'Next Page', it keeps flashing 'Saving... please don't close this window yet'
I can only progress to the next page by closing this and re-opening.

Same behaviour when I press 'Save' instead.

**Comment by MaximMoinat** [comment]
Note: the entry is saved and after re-opening I am able to edit the other pages.

Note2: Same happens when saving on any other page of the entry.

**Comment by alina-trifan** [comment]
Corrected
