### ISSUE TITLE
Questionnaire update

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/DatabaseCatalogue#33]
- [x] Question 2.12 should be a check box
- [x] Add question to upload the logo

Find attached an updated list of questions. Red means remove question, Green means add or update.

[DataCatalogue_May2020.xlsx](https://github.com/EHDEN/DatabaseCatalogue/files/4646337/DataCatalogue_May2020.xlsx)

**Comment by joaorafaelalmeida** [comment]
Hi Peter,
I added this new questionnaire in production with the changes you also mentioned in this issue (Question 2.12 and Logo).
