### ISSUE TITLE
4.03 add ICPC 1 and 2

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/DatabaseCatalogue#7]
ICPC should be replaced by ICPC1 and ICPC2

**Comment by PRijnbeek** [comment]
In general we may need to clean the list of local coding systems per domain, for example 5.03 has RxNorm for devices.

**Comment by alina-trifan** [comment]
> ICPC should be replaced by ICPC1 and ICPC2

Done

> In general we may need to clean the list of local coding systems per domain, for example 5.03 has RxNorm for devices.

Not sure what you mean by this.

**Comment by PRijnbeek** [comment]
I mean that i think i now copied the vocabularies for all domains, but some are related only to drugs for example. I think we need to discuss how to best provide the information for the domains. Maybe i kind of table as I have seen in the ADVANCE fingerprint would actually be best.

**Comment by alina-trifan** [comment]
OK, will leave this open for discussion.

**Comment by alina-trifan** [comment]
I will close this issue as I think we will have an updated template, so the discussion will no longer be continued here.
