### ISSUE TITLE
Saving is a bit slow

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/DatabaseCatalogue#9]
When I fill in the questionnaire can switch to next set it is being saved (which is fine). It does take some time to save. Maybe something to look into at a later point in time. Maybe this depends on the current infrastructure.

**Comment by alina-trifan** [comment]
This is currently in progress - we identified several pages that load too slow and we are working on speeding up their rendering

**Comment by alina-trifan** [comment]
Done
